name: Regression Suit

on:

 push:
   branches:
     -master
pull_request:
  branches:
    -master

jobs:
  run_tests:
    runs_on: ubuntu-test

   steps:
      - name: Chcekout code
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setu-python@v2
        with:
          python-version: '3.13.0'
  
      - name: Install dependecies
        run: |
          python -m pip install -upgrade
          pip install -r requirements.txt
  
      - name: Run tests
        run: |
          pytest -s -v --html=Reports/Reporttdfail.html test_users_api.py
          
      
      - name: Run tests
        uses: action/upload-artifact@v1
        with:
          name: pytest-report
          path: report.html
